apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-wordpress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/deegraee/nginx-wordpress-kube'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true