apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: proxy-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 34.46.112.76
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80